# Generated by Django 4.1 on 2022-08-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newstype",
            name="type",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
