# Generated by Django 4.1 on 2022-08-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_newstype_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsTopic",
        ),
        migrations.DeleteModel(
            name="NewsType",
        ),
    ]
