# Generated by Django 4.1 on 2022-08-31 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_posts"),
    ]

    operations = [
        migrations.DeleteModel(
            name="posts",
        ),
    ]
