# Generated by Django 4.1 on 2022-09-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="updated_date",
            field=models.DateTimeField(null=True),
        ),
    ]
