# Generated by Django 4.1 on 2022-08-25 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=50, unique=True)),
                ("car_model", models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="Piece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("piece_name", models.CharField(max_length=200)),
                ("price", models.IntegerField(max_length=3)),
                ("is_available", models.BooleanField()),
                (
                    "piece_car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="pages.cartype",
                    ),
                ),
            ],
        ),
    ]
