# Generated by Django 4.1 on 2022-08-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_rename_piece_car_model_piece_car_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartype",
            name="car_name",
            field=models.CharField(max_length=50),
        ),
    ]
