# Generated by Django 4.1 on 2022-08-31 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_views"),
    ]

    operations = [
        migrations.RenameField(
            model_name="piece",
            old_name="car_id",
            new_name="car",
        ),
    ]
