# Generated by Django 4.1 on 2022-08-31 15:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0007_rename_car_id_piece_car"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Views",
            new_name="Comments",
        ),
    ]
