# Generated by Django 4.1 on 2022-08-31 15:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0008_rename_views_comments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="posts",
        ),
    ]
