# Generated by Django 4.1 on 2022-09-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_rename_comments_posts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="piece",
            name="car",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="topic",
        ),
        migrations.DeleteModel(
            name="CarType",
        ),
        migrations.DeleteModel(
            name="Piece",
        ),
        migrations.DeleteModel(
            name="posts",
        ),
    ]
